config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :jewelleries, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
    get "listings"
    end
    resources :loans, only: [:new, :create]
  end
  resources :loans, only: [:index, :show, :destroy]

  get "/profile", to: "profile#profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jewellery.rb
class Jewellery < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_many :loans

  def unavailable_dates
    loans.pluck(:from, :to).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :jewellery
  before_create :assign_total_price
  validates :from, :to, presence: true, availability: true
  validate :from_after_to

  def assign_total_price
    self.total_price = extract_total_price
  end

  def extract_total_price
    extract_days * self.jewellery.price
  end

  def extract_days
    ((self.to - self.from) / 3600 / 24).to_i
 end
end

private

def from_after_to
  return if from.blank? || to.blank?

   if to < from
     errors.add(:to, "must be after the start date")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :jewelleries
  has_many :loans
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :listings], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :listings], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def after_sign_in_path_for(ressource)
    jewelleries_path
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/jewelleries_controller.rb
class JewelleriesController < ApplicationController
  before_action :set_jewellery, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @query = params[:query]
      @jewelleries = policy_scope(Jewellery).where("name LIKE ?", "%#{@query}%")
    else
      @jewelleries = policy_scope(Jewellery)
    end
  end

  def listings
    @jewelleries = policy_scope(Jewellery).where(:user => current_user)
  end

  def show
    @jewellery
    @loan = Loan.new
  end

  def new
    @jewellery = Jewellery.new
    authorize @jewellery
  end

  def create
    @jewellery = Jewellery.new(jewellery_params)
    @jewellery.user = current_user
    authorize @jewellery
    if @jewellery.save
      redirect_to jewelleries_path(@jewellery)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @jewellery.update(jewellery_params)
    redirect_to jewellery_path(@jewellery)
  end

  def destroy
    @jewellery.destroy
    redirect_to jewelleries_path
  end

  private

  def jewellery_params
    params.require(:jewellery).permit(:name, :description, :price, photos: [])
  end

  def set_jewellery
    @jewellery = Jewellery.find(params[:id])
    authorize @jewellery
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :destroy]

  def index
    @loans = policy_scope(Loan).where(:user => current_user)
  end

  def show
  end

  def new
    @jewellery = Jewellery.find(params[:jewellery_id])
    @loan = Loan.new
    @loans = Loan.all
    authorize @loan
  end

  def create
    @loan = Loan.new(loan_params)
    @jewellery = Jewellery.find(params[:jewellery_id])
    @loan.jewellery = @jewellery
    @loan.user = current_user
    authorize @loan
    if @loan.save
      redirect_to loan_path(@loan)
    else
      render :new
    end
  end

  def destroy
    @jewellery = @loan.jewellery
    @loan.destroy
    redirect_to jewellery_path(@jewellery)
  end

  private

  def set_loan
    @loan = Loan.find(params[:id])
    authorize @loan
  end

  def loan_params
    params.require(:loan).permit(:from, :to)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jewelleries/_jewellery_form.html.erb
<!-- <!DOCTYPE html>
<html>
 <FORM>
    <P>
    Name: <INPUT type="text" name="Name"><BR>
    Description: <INPUT type="text" name="description"><BR>
    Price: <INPUT type="text" name="price"><BR>
      Photo: <INPUT type="file" name="photo"><BR>
    <INPUT type="submit" value="Find"> <INPUT type="reset">
          <head>
    <title>Title of the document</title>
    <style>
body {
  color:pink
}
</style>
  </head>
  <body style="background-color:#000000;">
    </P>
 </FORM> -->

<div class="m-5">
<%= simple_form_for(@jewellery) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
</div>
<% end %>

app/views/jewelleries/_new_jewellery_form.html.erb
<div class="container">
<%= simple_form_for(@jewellery) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions btn btn-primary">
    <%= f.button :submit %>
  </div>
</div>
<% end %>

app/views/jewelleries/edit.html.erb
<h1 style="color:pink;"
class="text-center"> Edit Jewellery
Listing </h1>
<%=render 'new_jewellery_form', jewellery:@jewellery %>
<%=link_to 'Back',jewelleries_path %>

app/views/jewelleries/index.html.erb
<br>
<h1 class="text-center gradient">Jewelleries</h1>
    <div class = "path">
    <%= form_tag jewelleries_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-path",
    placeholder: "Find a jewellery"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
<br>
</div>

<div class="row text-center mt-3">
    <div class="col">
    <% if @query %>
        <p style = "color:pink;">You searched for <strong><%= @query %></strong>. We found <%= @jewelleries.count %> jewelleries out of our <%= Jewellery.count %> on our website.</p>
      <% else %>
        <p style = "color:pink;">All <%= Jewellery.count %> jewelleries.</p>
      <% end %>
    </div>
  </div>
  <div class="container2">
   <div class="wrapper">
    <% @jewelleries.each do |jewellery| %>
    <%= link_to jewellery do%>
    <div class="card">
      <% if jewellery.photos.attached? %>
      <div class="card-image" style="background-image: url('<%= cl_image_path jewellery.photos.first.key, height: 200, width: 300, crop: :fill %>')"></div>
      <% else %>
         <div class="card-image2"><%= image_tag 'diamond_placeholder.png' %></div>
      <% end %>
      <div class="card-body">
          <h5 style=""><%= jewellery.name %></h5>
          <p class="ml-3 mt-1" style ="font-size: 20px;"> £<%= jewellery.price %></p>
      </div>
    </div>
    <% end %>
<% end %>
</div>
</div>
<div class="form-actions text-center mb-5">
  <h1 style="font-size: 60px;">
<%= link_to 'add your own here!', new_jewellery_path %>
  </h1>
</div>
<br>

app/views/jewelleries/listings.html.erb
 <div class="wrapper">
    <% @jewelleries.each do |jewellery| %>
    <%= link_to jewellery do%>
    <div class="card">
      <% if jewellery.photos.attached? %>
      <div class="card-image" style="background-image: url('<%= cl_image_path jewellery.photos.first.key, height: 200, width: 300, crop: :fill %>')"></div>
      <% else %>
      <div class="card-image2"><%= image_tag 'diamond_placeholder.png' %></div>
      <% end %>
      <div class="card-body">
          <h5 style="color: pink;"><%= jewellery.name %></h5>
      </div>
    </div>
    <% end %>
<% end %>
</div>
<br>
<div class = "wrap">
<%= link_to 'New Jewellery', new_jewellery_path, class: "button" %>
</div>

app/views/jewelleries/new.html.erb
<br>
<h1 style="color:pink;" class="text-center">New Jewellery Listing</h1>

<%= render 'new_jewellery_form', jewellery: @jewellery %>

<%= link_to 'Back', jewelleries_path %>

app/views/jewelleries/show.html.erb
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
<div class = "card-show">
<p>
  <h2 class="jewellery" style="color: pink;"> <%=  @jewellery.name %></h2>
</p>


  <p style ="color:grey;"> <strong>Description:</strong>
  <%= @jewellery.description %> </p>


  <p style="color:grey;"> <strong>Price:</strong>
 £<%= @jewellery.price %> per day
</p>

</p>
</div>
<div class="show-image row">
<% @jewellery.photos.each do |photo| %>
  <div class="col-sm-12 col-md-6 col-lg-3"><%= cl_image_tag photo.key, height: 200, width: 300, crop: :fill %></div>
<% end %>
</div>
<% if @jewellery.loans.where(user: current_user).present? %>
<h4 class="text-center gradient"><%= link_to "SHOW LOAN", loans_path %></h4>
<% elsif current_user != @jewellery.user %>
<h2 class="text-center gradient my-5"><%= link_to "RENT THIS ITEM!", new_jewellery_loan_path(@jewellery) %></h2>
<% end %>
<div class="text-center">
<%= link_to jewelleries_path do %>
<button class="btn btn-primary mx-1">back</button>
<% end %>
<% if policy(@jewellery).update? %>
<%= link_to edit_jewellery_path do %>
<button class="btn btn-primary mx-1">edit</button>
<% end %>
<% end %>
<% if policy(@jewellery).destroy? %>
<%= link_to @jewellery, method: :delete, data: { confirm: 'Are you sure?'} do %>
<button class="btn btn-primary mx-1">delete</button>
<% end %>
<% end %>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirJewellery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

  </head>
<body style="background-color:black;">
  <div class="page-container">
  <div class="navbar-container"><%= render "shared/navbar" %></div>
  <div class="content-container"><%= yield %></div>
  <div class="footer-container"><%= render "shared/footer" %></div>
</div>
    <% if notice %>
    <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
  </body>
</html>

app/views/loans/index.html.erb
<div class="wrapper">
    <% @loans.each do |loan| %>
    <%= link_to loan do%>
    <div class="card">
      <div class="card-body">
        <p><%= loan.from.strftime("%A, %b %d") %> to
        <%= loan.to.strftime("%A, %b %d") %> </p>
       <p> £<%= loan.total_price %> </p>
      </div>
    </div>
    <% end %>
<% end %>
</div>



<div class ="text-center w-100 ml-5">
<%= link_to "Back", jewelleries_path(@jewelleries), class: "button" %>
</div>

app/views/loans/new.html.erb
<div class="form-new mt-5">
<div class="widget-content d-none" data-unavailable="<%= @jewellery.unavailable_dates.to_json %>"></div>

<%= simple_form_for([@jewellery, @loan]) do |f| %>
  <%= f.input :from, as: :string, label: "Dates", placeholder: "From", wrapper_html: { class: "inline_field_wrapper" } %>
  <%= f.input :to, as: :string, label: '&nbsp;'.html_safe, placeholder: "To", disabled: true, wrapper_html: { class: "inline_field_wrapper" } %>
  <%= f.submit "book", class: "btn btn-primary btn-lg btn-block btn-booking" %>
<% end %>
  <%= link_to jewellery_path(@jewellery) do %>
<button class="btn btn-primary mt-5">back</button>
<% end %>
</div>

app/views/loans/show.html.erb
<div class="wrapper">
<div class= "card-price">
<h2 style ="color:pink;">  Your loan is <%= @loan.jewellery.name %></h2>
  <p style = "color:pink;"> <%= @loan.jewellery.description %></p>
  <p style ="color:pink;"> Your total price will be £ <%= @loan.total_price %></p>
<p><%= link_to loan_path(@loan),

      method: :delete,
      data: { confirm: "Are you sure?" } do %>
      <i class="fas fa-minus-circle"></i>
      <% end %></p>

    </div>
   <div class= "card-price"> 
<p style = "color:pink";>   <%= link_to "Would you like to loan another item?" , jewelleries_path %> </p>
</div>
<p style = "color:pink;"> By loaning this item you have helped save the planet, thank you! </p>
</div>
<div class ="wrap ml-5">

 <%= link_to "Back", loans_path(@loans), class: "button" %>
</div>
</div>

app/views/pages/home.html.erb
<div class="color" style="background-color:black; height: 100vh">

<div class ="rainbow-text">
<h1> AirJewellery </h1>
</div>
</div>

app/views/shared/_footer.html.erb
<footer class="page-footer" style = "color:pink;" >

  <!-- Footer Links -->
  <div class="container" style = "background-color: black; border: solid black; box-shadow: 0 4px 8px 0 pink;">

    <!-- Grid row-->
    <div class="row text-center d-flex justify-content-center pt-5 mb-3">

      <!-- Grid column -->
      <div class="col-md-2 mb-1">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">About us</a>
        </h6>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->

      <!-- Grid column -->

      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-1">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">Help</a>
        </h6>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-1">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">Contact</a>
        </h6>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->
    <hr class="rgba-white-light" style="margin: 0 15%;">

    <!-- Grid row-->
    <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">

      <!-- Grid column -->
      <div class="mx-5 mb-2">
        <p style="line-height: 1.7rem">Sed ut perspiciatis unde omnis iste natus error sit voluptatem
          accusantium doloremque laudantium, totam rem
          aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt
          explicabo.
          Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur.</p>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->
    <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">

    <!-- Grid row-->
    <div class="row pb-3">

      <!-- Grid column -->
      <div class="col-md-12">

        <div class="mb-3 text-center">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f fa-lg white-text mr-4"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter fa-lg white-text mr-4"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g fa-lg white-text mr-4"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in fa-lg white-text mr-4"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram fa-lg white-text mr-4"> </i>
          </a>
          <!--Pinterest-->
          <a class="pin-ic">
            <i class="fab fa-pinterest fa-lg white-text"> </i>
          </a>

        </div>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Cadence
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "diamond.jpeg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", jewelleries_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "diamond.jpeg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My loans", loans_path, class: "dropdown-item" %>
            <%= link_to "My listings",listings_jewelleries_path , class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>